// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agntcoin/agntcoin/v1/bond.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Bond defines slashable collateral held by the protocol. A participant
// (poster) locks `amount` behind a claim/behavior; a designated neutral
// `slasher` either releases it (exonerate -> refund the poster) or slashes it
// (punish -> collateral to a beneficiary, or burned). The security-critical
// property — what makes it a deterrent and not a refundable deposit — is that
// the poster can NEVER self-withdraw (only the slasher resolves it).
// status is one of: "active" | "released" | "slashed".
type Bond struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Poster  string `protobuf:"bytes,2,opt,name=poster,proto3" json:"poster,omitempty"`
	Amount  uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose string `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Slasher string `protobuf:"bytes,5,opt,name=slasher,proto3" json:"slasher,omitempty"`
	Status  string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Ref     string `protobuf:"bytes,7,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (m *Bond) Reset()         { *m = Bond{} }
func (m *Bond) String() string { return proto.CompactTextString(m) }
func (*Bond) ProtoMessage()    {}
func (*Bond) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b6de48bfb5669e, []int{0}
}
func (m *Bond) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bond.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bond.Merge(m, src)
}
func (m *Bond) XXX_Size() int {
	return m.Size()
}
func (m *Bond) XXX_DiscardUnknown() {
	xxx_messageInfo_Bond.DiscardUnknown(m)
}

var xxx_messageInfo_Bond proto.InternalMessageInfo

func (m *Bond) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bond) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *Bond) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Bond) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Bond) GetSlasher() string {
	if m != nil {
		return m.Slasher
	}
	return ""
}

func (m *Bond) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Bond) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func init() {
	proto.RegisterType((*Bond)(nil), "agntcoin.agntcoin.v1.Bond")
}

func init() { proto.RegisterFile("agntcoin/agntcoin/v1/bond.proto", fileDescriptor_78b6de48bfb5669e) }

var fileDescriptor_78b6de48bfb5669e = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xe3, 0x34, 0xa4, 0xc2, 0x03, 0x42, 0x16, 0x42, 0x9e, 0x4c, 0xc5, 0xd4, 0x29, 0x51,
	0xc5, 0x1b, 0x74, 0x63, 0xed, 0xc8, 0xe6, 0x34, 0xa6, 0xb5, 0x68, 0x7d, 0x2d, 0xdf, 0x9b, 0x0a,
	0x78, 0x0a, 0x1e, 0x82, 0x87, 0x61, 0xec, 0xc8, 0x88, 0x92, 0x17, 0x41, 0x71, 0xd2, 0x76, 0xfb,
	0xbe, 0x73, 0xfc, 0x23, 0x1d, 0xfe, 0xa0, 0x37, 0x8e, 0xd6, 0x60, 0x5d, 0x79, 0x86, 0xc3, 0xa2,
	0xac, 0xc0, 0xd5, 0x85, 0x0f, 0x40, 0x20, 0xee, 0x4e, 0x79, 0x71, 0x86, 0xc3, 0xe2, 0xf1, 0x9b,
	0xf1, 0x6c, 0x09, 0xae, 0x16, 0x37, 0x3c, 0xb5, 0xb5, 0x64, 0x33, 0x36, 0xcf, 0x56, 0xa9, 0xad,
	0xc5, 0x3d, 0xcf, 0x3d, 0x20, 0x99, 0x20, 0xd3, 0x19, 0x9b, 0x5f, 0xaf, 0x46, 0xeb, 0x73, 0xbd,
	0x87, 0xc6, 0x91, 0x9c, 0xc4, 0xb3, 0xa3, 0x09, 0xc9, 0xa7, 0xbe, 0x09, 0x1e, 0xd0, 0xc8, 0x2c,
	0x5e, 0x38, 0x69, 0xdf, 0xe0, 0x4e, 0xe3, 0xd6, 0x04, 0x79, 0x35, 0x34, 0xa3, 0xf6, 0x6f, 0x21,
	0x69, 0x6a, 0x50, 0xe6, 0xc3, 0x1f, 0x83, 0x89, 0x5b, 0x3e, 0x09, 0xe6, 0x55, 0x4e, 0x63, 0xd8,
	0xe3, 0xf2, 0xf9, 0xa7, 0x55, 0xec, 0xd8, 0x2a, 0xf6, 0xd7, 0x2a, 0xf6, 0xd5, 0xa9, 0xe4, 0xd8,
	0xa9, 0xe4, 0xb7, 0x53, 0xc9, 0x4b, 0xb9, 0xb1, 0xb4, 0x6d, 0xaa, 0x62, 0x0d, 0xfb, 0xf2, 0x13,
	0x76, 0xa4, 0xdd, 0x9b, 0x45, 0xbc, 0x8c, 0xf0, 0x7e, 0x41, 0xfa, 0xf0, 0x06, 0xab, 0x3c, 0xce,
	0xf1, 0xf4, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x8b, 0x5a, 0x64, 0x31, 0x01, 0x00, 0x00,
}

func (m *Bond) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bond) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bond) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ref) > 0 {
		i -= len(m.Ref)
		copy(dAtA[i:], m.Ref)
		i = encodeVarintBond(dAtA, i, uint64(len(m.Ref)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintBond(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Slasher) > 0 {
		i -= len(m.Slasher)
		copy(dAtA[i:], m.Slasher)
		i = encodeVarintBond(dAtA, i, uint64(len(m.Slasher)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Purpose) > 0 {
		i -= len(m.Purpose)
		copy(dAtA[i:], m.Purpose)
		i = encodeVarintBond(dAtA, i, uint64(len(m.Purpose)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Poster) > 0 {
		i -= len(m.Poster)
		copy(dAtA[i:], m.Poster)
		i = encodeVarintBond(dAtA, i, uint64(len(m.Poster)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBond(dAtA []byte, offset int, v uint64) int {
	offset -= sovBond(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Bond) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovBond(uint64(m.Id))
	}
	l = len(m.Poster)
	if l > 0 {
		n += 1 + l + sovBond(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovBond(uint64(m.Amount))
	}
	l = len(m.Purpose)
	if l > 0 {
		n += 1 + l + sovBond(uint64(l))
	}
	l = len(m.Slasher)
	if l > 0 {
		n += 1 + l + sovBond(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovBond(uint64(l))
	}
	l = len(m.Ref)
	if l > 0 {
		n += 1 + l + sovBond(uint64(l))
	}
	return n
}

func sovBond(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBond(x uint64) (n int) {
	return sovBond(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Bond) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bond: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bond: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poster", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Poster = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Purpose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Purpose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slasher", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slasher = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ref", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ref = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBond(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBond
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBond
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBond
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBond
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBond        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBond          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBond = fmt.Errorf("proto: unexpected end of group")
)
