// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agntcoin/agntcoin/v1/contribution.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ContributionAward records a beta proof-of-useful-work author mint.
//
// In 0.4.0-beta.1 this is ANCHOR-mediated: a founder/trust-root accepts a
// small protocol contribution and mints capped AGNT to the author while pinning
// the public evidence by hash. The full PR, patch, tests, and rationale stay
// off-chain; the chain records integrity and payout.
type ContributionAward struct {
	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Anchor         string `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Recipient      string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	RepoUrl        string `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	PrUrl          string `protobuf:"bytes,5,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	CommitSha      string `protobuf:"bytes,6,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	ArtifactUri    string `protobuf:"bytes,7,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	ArtifactSha256 string `protobuf:"bytes,8,opt,name=artifact_sha256,json=artifactSha256,proto3" json:"artifact_sha256,omitempty"`
	EvidenceSha256 string `protobuf:"bytes,9,opt,name=evidence_sha256,json=evidenceSha256,proto3" json:"evidence_sha256,omitempty"`
	Scope          string `protobuf:"bytes,10,opt,name=scope,proto3" json:"scope,omitempty"`
	RationaleHash  string `protobuf:"bytes,11,opt,name=rationale_hash,json=rationaleHash,proto3" json:"rationale_hash,omitempty"`
	Amount         uint64 `protobuf:"varint,12,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *ContributionAward) Reset()         { *m = ContributionAward{} }
func (m *ContributionAward) String() string { return proto.CompactTextString(m) }
func (*ContributionAward) ProtoMessage()    {}
func (*ContributionAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_864443848c70988c, []int{0}
}
func (m *ContributionAward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContributionAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContributionAward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContributionAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContributionAward.Merge(m, src)
}
func (m *ContributionAward) XXX_Size() int {
	return m.Size()
}
func (m *ContributionAward) XXX_DiscardUnknown() {
	xxx_messageInfo_ContributionAward.DiscardUnknown(m)
}

var xxx_messageInfo_ContributionAward proto.InternalMessageInfo

func (m *ContributionAward) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContributionAward) GetAnchor() string {
	if m != nil {
		return m.Anchor
	}
	return ""
}

func (m *ContributionAward) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *ContributionAward) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

func (m *ContributionAward) GetPrUrl() string {
	if m != nil {
		return m.PrUrl
	}
	return ""
}

func (m *ContributionAward) GetCommitSha() string {
	if m != nil {
		return m.CommitSha
	}
	return ""
}

func (m *ContributionAward) GetArtifactUri() string {
	if m != nil {
		return m.ArtifactUri
	}
	return ""
}

func (m *ContributionAward) GetArtifactSha256() string {
	if m != nil {
		return m.ArtifactSha256
	}
	return ""
}

func (m *ContributionAward) GetEvidenceSha256() string {
	if m != nil {
		return m.EvidenceSha256
	}
	return ""
}

func (m *ContributionAward) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *ContributionAward) GetRationaleHash() string {
	if m != nil {
		return m.RationaleHash
	}
	return ""
}

func (m *ContributionAward) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*ContributionAward)(nil), "agntcoin.agntcoin.v1.ContributionAward")
}

func init() {
	proto.RegisterFile("agntcoin/agntcoin/v1/contribution.proto", fileDescriptor_864443848c70988c)
}

var fileDescriptor_864443848c70988c = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x4e, 0x2a, 0x31,
	0x14, 0xc6, 0x99, 0xb9, 0x30, 0x40, 0xe1, 0x72, 0x73, 0x1b, 0xee, 0x4d, 0x4d, 0x74, 0x82, 0x26,
	0x06, 0x56, 0x4c, 0xd0, 0xe8, 0x5e, 0xdd, 0xe8, 0x16, 0xc2, 0xc6, 0xcd, 0xa4, 0x74, 0x2a, 0x6d,
	0x9c, 0x69, 0x27, 0x6d, 0x07, 0xff, 0x3c, 0x85, 0x8f, 0xe5, 0x92, 0xa5, 0x4b, 0x03, 0xaf, 0xe0,
	0x03, 0x98, 0xe9, 0x30, 0x83, 0xbb, 0xf3, 0xfd, 0xbe, 0x5f, 0x9a, 0xe6, 0x1c, 0x30, 0xc4, 0x4b,
	0x61, 0x88, 0xe4, 0x22, 0xa8, 0x86, 0xd5, 0x24, 0x20, 0x52, 0x18, 0xc5, 0x17, 0x99, 0xe1, 0x52,
	0x8c, 0x53, 0x25, 0x8d, 0x84, 0xfd, 0xb2, 0x1f, 0x57, 0xc3, 0x6a, 0x72, 0xf2, 0xe5, 0x82, 0xbf,
	0x37, 0x3f, 0xe4, 0xab, 0x27, 0xac, 0x22, 0xd8, 0x03, 0x2e, 0x8f, 0x90, 0x33, 0x70, 0x46, 0xf5,
	0xa9, 0xcb, 0x23, 0xf8, 0x1f, 0x78, 0x58, 0x10, 0x26, 0x15, 0x72, 0x07, 0xce, 0xa8, 0x3d, 0xdd,
	0x25, 0x78, 0x08, 0xda, 0x8a, 0x12, 0x9e, 0x72, 0x2a, 0x0c, 0xfa, 0x65, 0xab, 0x3d, 0x80, 0x07,
	0xa0, 0xa5, 0x68, 0x2a, 0xc3, 0x4c, 0xc5, 0xa8, 0x6e, 0xcb, 0x66, 0x9e, 0xe7, 0x2a, 0x86, 0xff,
	0x80, 0x97, 0x2a, 0x5b, 0x34, 0x6c, 0xd1, 0x48, 0x55, 0x8e, 0x8f, 0x00, 0x20, 0x32, 0x49, 0xb8,
	0x09, 0x35, 0xc3, 0xc8, 0x2b, 0x1e, 0x2c, 0xc8, 0x8c, 0x61, 0x78, 0x0c, 0xba, 0x58, 0x19, 0xfe,
	0x80, 0x89, 0x09, 0x33, 0xc5, 0x51, 0xd3, 0x0a, 0x9d, 0x92, 0xcd, 0x15, 0x87, 0x43, 0xf0, 0xa7,
	0x52, 0x34, 0xc3, 0x67, 0x17, 0x97, 0xa8, 0x65, 0xad, 0x5e, 0x89, 0x67, 0x96, 0xe6, 0x22, 0x5d,
	0xf1, 0x88, 0x0a, 0x42, 0x4b, 0xb1, 0x5d, 0x88, 0x25, 0xde, 0x89, 0x7d, 0xd0, 0xd0, 0x44, 0xa6,
	0x14, 0x81, 0xe2, 0xa7, 0x36, 0xc0, 0x53, 0xd0, 0x53, 0x38, 0x5f, 0x18, 0x8e, 0x69, 0xc8, 0xb0,
	0x66, 0xa8, 0x63, 0xeb, 0xdf, 0x15, 0xbd, 0xc5, 0x9a, 0xd9, 0xc5, 0x25, 0x32, 0x13, 0x06, 0x75,
	0xed, 0x32, 0x77, 0xe9, 0xfa, 0xee, 0x7d, 0xe3, 0x3b, 0xeb, 0x8d, 0xef, 0x7c, 0x6e, 0x7c, 0xe7,
	0x6d, 0xeb, 0xd7, 0xd6, 0x5b, 0xbf, 0xf6, 0xb1, 0xf5, 0x6b, 0xf7, 0xc1, 0x92, 0x1b, 0x96, 0x2d,
	0xc6, 0x44, 0x26, 0xc1, 0xab, 0x8c, 0x0d, 0x16, 0x8f, 0x5c, 0xeb, 0xfd, 0x71, 0x9f, 0xf7, 0xa3,
	0x79, 0x49, 0xa9, 0x5e, 0x78, 0xf6, 0xbc, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xc7,
	0x59, 0x7b, 0x09, 0x02, 0x00, 0x00,
}

func (m *ContributionAward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContributionAward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContributionAward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x60
	}
	if len(m.RationaleHash) > 0 {
		i -= len(m.RationaleHash)
		copy(dAtA[i:], m.RationaleHash)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.RationaleHash)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Scope) > 0 {
		i -= len(m.Scope)
		copy(dAtA[i:], m.Scope)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Scope)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.EvidenceSha256) > 0 {
		i -= len(m.EvidenceSha256)
		copy(dAtA[i:], m.EvidenceSha256)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.EvidenceSha256)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ArtifactSha256) > 0 {
		i -= len(m.ArtifactSha256)
		copy(dAtA[i:], m.ArtifactSha256)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.ArtifactSha256)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ArtifactUri) > 0 {
		i -= len(m.ArtifactUri)
		copy(dAtA[i:], m.ArtifactUri)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.ArtifactUri)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CommitSha) > 0 {
		i -= len(m.CommitSha)
		copy(dAtA[i:], m.CommitSha)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.CommitSha)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PrUrl) > 0 {
		i -= len(m.PrUrl)
		copy(dAtA[i:], m.PrUrl)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.PrUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RepoUrl) > 0 {
		i -= len(m.RepoUrl)
		copy(dAtA[i:], m.RepoUrl)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.RepoUrl)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Anchor) > 0 {
		i -= len(m.Anchor)
		copy(dAtA[i:], m.Anchor)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Anchor)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintContribution(dAtA []byte, offset int, v uint64) int {
	offset -= sovContribution(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ContributionAward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovContribution(uint64(m.Id))
	}
	l = len(m.Anchor)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.RepoUrl)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.PrUrl)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.CommitSha)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.ArtifactUri)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.ArtifactSha256)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.EvidenceSha256)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.Scope)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.RationaleHash)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovContribution(uint64(m.Amount))
	}
	return n
}

func sovContribution(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContribution(x uint64) (n int) {
	return sovContribution(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ContributionAward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContributionAward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContributionAward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Anchor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepoUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepoUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitSha", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitSha = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArtifactUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArtifactUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArtifactSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArtifactSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RationaleHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RationaleHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipContribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContribution(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContribution
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContribution
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContribution
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContribution        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContribution          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContribution = fmt.Errorf("proto: unexpected end of group")
)
