// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agntcoin/agntcoin/v1/emission.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EmissionState tracks the monetary-policy primitive for protocol-minted AGNT.
//
// The scheduled reward for an epoch is split into actual mined supply and
// burned-unclaimed supply:
//
//	scheduled_reward = actual_mined + burned_unclaimed
//
// This keeps MAX_SUPPLY as a hard cap while letting unused epoch issuance expire
// forever instead of rolling forward.
type EmissionState struct {
	MaxSupply            uint64 `protobuf:"varint,1,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	EpochLengthSeconds   uint64 `protobuf:"varint,2,opt,name=epoch_length_seconds,json=epochLengthSeconds,proto3" json:"epoch_length_seconds,omitempty"`
	EpochRewardDivisor   uint64 `protobuf:"varint,3,opt,name=epoch_reward_divisor,json=epochRewardDivisor,proto3" json:"epoch_reward_divisor,omitempty"`
	GenesisTime          int64  `protobuf:"varint,4,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	CurrentEpoch         uint64 `protobuf:"varint,5,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	EpochStartedAt       int64  `protobuf:"varint,6,opt,name=epoch_started_at,json=epochStartedAt,proto3" json:"epoch_started_at,omitempty"`
	EpochScheduled       uint64 `protobuf:"varint,7,opt,name=epoch_scheduled,json=epochScheduled,proto3" json:"epoch_scheduled,omitempty"`
	EpochMined           uint64 `protobuf:"varint,8,opt,name=epoch_mined,json=epochMined,proto3" json:"epoch_mined,omitempty"`
	TotalMined           uint64 `protobuf:"varint,9,opt,name=total_mined,json=totalMined,proto3" json:"total_mined,omitempty"`
	TotalBurnedUnclaimed uint64 `protobuf:"varint,10,opt,name=total_burned_unclaimed,json=totalBurnedUnclaimed,proto3" json:"total_burned_unclaimed,omitempty"`
}

func (m *EmissionState) Reset()         { *m = EmissionState{} }
func (m *EmissionState) String() string { return proto.CompactTextString(m) }
func (*EmissionState) ProtoMessage()    {}
func (*EmissionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_36331ed936e43089, []int{0}
}
func (m *EmissionState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmissionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmissionState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmissionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionState.Merge(m, src)
}
func (m *EmissionState) XXX_Size() int {
	return m.Size()
}
func (m *EmissionState) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionState.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionState proto.InternalMessageInfo

func (m *EmissionState) GetMaxSupply() uint64 {
	if m != nil {
		return m.MaxSupply
	}
	return 0
}

func (m *EmissionState) GetEpochLengthSeconds() uint64 {
	if m != nil {
		return m.EpochLengthSeconds
	}
	return 0
}

func (m *EmissionState) GetEpochRewardDivisor() uint64 {
	if m != nil {
		return m.EpochRewardDivisor
	}
	return 0
}

func (m *EmissionState) GetGenesisTime() int64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

func (m *EmissionState) GetCurrentEpoch() uint64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *EmissionState) GetEpochStartedAt() int64 {
	if m != nil {
		return m.EpochStartedAt
	}
	return 0
}

func (m *EmissionState) GetEpochScheduled() uint64 {
	if m != nil {
		return m.EpochScheduled
	}
	return 0
}

func (m *EmissionState) GetEpochMined() uint64 {
	if m != nil {
		return m.EpochMined
	}
	return 0
}

func (m *EmissionState) GetTotalMined() uint64 {
	if m != nil {
		return m.TotalMined
	}
	return 0
}

func (m *EmissionState) GetTotalBurnedUnclaimed() uint64 {
	if m != nil {
		return m.TotalBurnedUnclaimed
	}
	return 0
}

func init() {
	proto.RegisterType((*EmissionState)(nil), "agntcoin.agntcoin.v1.EmissionState")
}

func init() {
	proto.RegisterFile("agntcoin/agntcoin/v1/emission.proto", fileDescriptor_36331ed936e43089)
}

var fileDescriptor_36331ed936e43089 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x40, 0xb3, 0xa4, 0x14, 0xea, 0xb6, 0x80, 0xac, 0x08, 0xf9, 0xc2, 0x52, 0xe8, 0x81, 0x9c,
	0xb2, 0x54, 0xf0, 0x03, 0x54, 0xf4, 0x80, 0x04, 0x97, 0x2c, 0x5c, 0xb8, 0x58, 0xce, 0x7a, 0xb4,
	0x6b, 0xb1, 0xb6, 0x57, 0xf6, 0x6c, 0x48, 0xf9, 0x0a, 0x7e, 0x82, 0x7f, 0xe1, 0xd8, 0x23, 0x47,
	0x94, 0xfc, 0x08, 0xca, 0x78, 0x93, 0x70, 0x1b, 0xbd, 0xf7, 0x3c, 0xbe, 0x0c, 0xbb, 0x54, 0xb5,
	0xc3, 0xca, 0x1b, 0x57, 0xec, 0x87, 0xe5, 0x55, 0x01, 0xd6, 0xc4, 0x68, 0xbc, 0x9b, 0x75, 0xc1,
	0xa3, 0xe7, 0x93, 0x9d, 0x9b, 0xed, 0x87, 0xe5, 0xd5, 0xcb, 0x5f, 0x63, 0x76, 0x7e, 0x33, 0x84,
	0x25, 0x2a, 0x04, 0xfe, 0x8c, 0x31, 0xab, 0x56, 0x32, 0xf6, 0x5d, 0xd7, 0xde, 0x8a, 0xec, 0x22,
	0x9b, 0x1e, 0xcd, 0x4f, 0xac, 0x5a, 0x95, 0x04, 0xf8, 0x6b, 0x36, 0x81, 0xce, 0x57, 0x8d, 0x6c,
	0xc1, 0xd5, 0xd8, 0xc8, 0x08, 0x95, 0x77, 0x3a, 0x8a, 0x7b, 0x14, 0x72, 0x72, 0x1f, 0x49, 0x95,
	0xc9, 0x1c, 0x5e, 0x04, 0xf8, 0xae, 0x82, 0x96, 0xda, 0x2c, 0x4d, 0xf4, 0x41, 0x8c, 0xff, 0x7b,
	0x31, 0x27, 0xf5, 0x3e, 0x19, 0xfe, 0x82, 0x9d, 0xd5, 0xe0, 0x20, 0x9a, 0x28, 0xd1, 0x58, 0x10,
	0x47, 0x17, 0xd9, 0x74, 0x3c, 0x3f, 0x1d, 0xd8, 0x67, 0x63, 0x81, 0x5f, 0xb2, 0xf3, 0xaa, 0x0f,
	0x01, 0x1c, 0x4a, 0x5a, 0x20, 0xee, 0xd3, 0xb6, 0xb3, 0x01, 0xde, 0x6c, 0x19, 0x9f, 0xb2, 0x27,
	0xe9, 0xe7, 0x88, 0x2a, 0x20, 0x68, 0xa9, 0x50, 0x1c, 0xd3, 0xae, 0x47, 0xc4, 0xcb, 0x84, 0xdf,
	0x21, 0x7f, 0xc5, 0x1e, 0x0f, 0x65, 0xd5, 0x80, 0xee, 0x5b, 0xd0, 0xe2, 0x01, 0x2d, 0x1c, 0xc2,
	0x1d, 0xe5, 0xcf, 0xd9, 0x69, 0x0a, 0xad, 0x71, 0xa0, 0xc5, 0x43, 0x8a, 0x18, 0xa1, 0x4f, 0x5b,
	0xb2, 0x0d, 0xd0, 0xa3, 0x6a, 0x87, 0xe0, 0x24, 0x05, 0x84, 0x52, 0xf0, 0x96, 0x3d, 0x4d, 0xc1,
	0xa2, 0x0f, 0x0e, 0xb4, 0xec, 0x5d, 0xd5, 0x2a, 0x63, 0x41, 0x0b, 0x46, 0xed, 0x84, 0xec, 0x35,
	0xc9, 0x2f, 0x3b, 0x77, 0xfd, 0xe1, 0xf7, 0x3a, 0xcf, 0xee, 0xd6, 0x79, 0xf6, 0x77, 0x9d, 0x67,
	0x3f, 0x37, 0xf9, 0xe8, 0x6e, 0x93, 0x8f, 0xfe, 0x6c, 0xf2, 0xd1, 0xd7, 0xa2, 0x36, 0xd8, 0xf4,
	0x8b, 0x59, 0xe5, 0x6d, 0xf1, 0xc3, 0xb7, 0xa8, 0xdc, 0x37, 0x13, 0xe3, 0xe1, 0x12, 0x56, 0x87,
	0x11, 0x6f, 0x3b, 0x88, 0x8b, 0x63, 0xba, 0x87, 0x37, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71,
	0x7b, 0xd3, 0xc4, 0x36, 0x02, 0x00, 0x00,
}

func (m *EmissionState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmissionState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmissionState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalBurnedUnclaimed != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.TotalBurnedUnclaimed))
		i--
		dAtA[i] = 0x50
	}
	if m.TotalMined != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.TotalMined))
		i--
		dAtA[i] = 0x48
	}
	if m.EpochMined != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.EpochMined))
		i--
		dAtA[i] = 0x40
	}
	if m.EpochScheduled != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.EpochScheduled))
		i--
		dAtA[i] = 0x38
	}
	if m.EpochStartedAt != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.EpochStartedAt))
		i--
		dAtA[i] = 0x30
	}
	if m.CurrentEpoch != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x28
	}
	if m.GenesisTime != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.GenesisTime))
		i--
		dAtA[i] = 0x20
	}
	if m.EpochRewardDivisor != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.EpochRewardDivisor))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochLengthSeconds != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.EpochLengthSeconds))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxSupply != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.MaxSupply))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEmission(dAtA []byte, offset int, v uint64) int {
	offset -= sovEmission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EmissionState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxSupply != 0 {
		n += 1 + sovEmission(uint64(m.MaxSupply))
	}
	if m.EpochLengthSeconds != 0 {
		n += 1 + sovEmission(uint64(m.EpochLengthSeconds))
	}
	if m.EpochRewardDivisor != 0 {
		n += 1 + sovEmission(uint64(m.EpochRewardDivisor))
	}
	if m.GenesisTime != 0 {
		n += 1 + sovEmission(uint64(m.GenesisTime))
	}
	if m.CurrentEpoch != 0 {
		n += 1 + sovEmission(uint64(m.CurrentEpoch))
	}
	if m.EpochStartedAt != 0 {
		n += 1 + sovEmission(uint64(m.EpochStartedAt))
	}
	if m.EpochScheduled != 0 {
		n += 1 + sovEmission(uint64(m.EpochScheduled))
	}
	if m.EpochMined != 0 {
		n += 1 + sovEmission(uint64(m.EpochMined))
	}
	if m.TotalMined != 0 {
		n += 1 + sovEmission(uint64(m.TotalMined))
	}
	if m.TotalBurnedUnclaimed != 0 {
		n += 1 + sovEmission(uint64(m.TotalBurnedUnclaimed))
	}
	return n
}

func sovEmission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEmission(x uint64) (n int) {
	return sovEmission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EmissionState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmissionState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmissionState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			m.MaxSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLengthSeconds", wireType)
			}
			m.EpochLengthSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLengthSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochRewardDivisor", wireType)
			}
			m.EpochRewardDivisor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochRewardDivisor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisTime", wireType)
			}
			m.GenesisTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenesisTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStartedAt", wireType)
			}
			m.EpochStartedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochStartedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochScheduled", wireType)
			}
			m.EpochScheduled = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochScheduled |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochMined", wireType)
			}
			m.EpochMined = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochMined |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMined", wireType)
			}
			m.TotalMined = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalMined |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurnedUnclaimed", wireType)
			}
			m.TotalBurnedUnclaimed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalBurnedUnclaimed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEmission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEmission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEmission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEmission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEmission = fmt.Errorf("proto: unexpected end of group")
)
