// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agntcoin/agntcoin/v1/evidence.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ScopedEvidenceVouch is a reputation-backed attestation over a specific piece
// of public evidence. It is not a coin-staked vouch: in the genesis beachhead,
// the founder/root may have reputation authority but intentionally has 0 AGNT.
//
// The vouch says "issuer believes recipient has demonstrated capability in
// scope, based on externally reviewable bytes whose hashes are pinned here."
// Later versions can add challenges, slashing, and expiry enforcement; beta.2
// records the public evidence trail without forcing a premine or faucet claim.
type ScopedEvidenceVouch struct {
	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Issuer         string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Recipient      string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Scope          string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Weight         uint64 `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	ArtifactUri    string `protobuf:"bytes,6,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	ArtifactSha256 string `protobuf:"bytes,7,opt,name=artifact_sha256,json=artifactSha256,proto3" json:"artifact_sha256,omitempty"`
	EvidenceUri    string `protobuf:"bytes,8,opt,name=evidence_uri,json=evidenceUri,proto3" json:"evidence_uri,omitempty"`
	EvidenceSha256 string `protobuf:"bytes,9,opt,name=evidence_sha256,json=evidenceSha256,proto3" json:"evidence_sha256,omitempty"`
	RationaleHash  string `protobuf:"bytes,10,opt,name=rationale_hash,json=rationaleHash,proto3" json:"rationale_hash,omitempty"`
	ExpiresAt      int64  `protobuf:"varint,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *ScopedEvidenceVouch) Reset()         { *m = ScopedEvidenceVouch{} }
func (m *ScopedEvidenceVouch) String() string { return proto.CompactTextString(m) }
func (*ScopedEvidenceVouch) ProtoMessage()    {}
func (*ScopedEvidenceVouch) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a73a065bf5dc8e, []int{0}
}
func (m *ScopedEvidenceVouch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScopedEvidenceVouch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScopedEvidenceVouch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScopedEvidenceVouch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopedEvidenceVouch.Merge(m, src)
}
func (m *ScopedEvidenceVouch) XXX_Size() int {
	return m.Size()
}
func (m *ScopedEvidenceVouch) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopedEvidenceVouch.DiscardUnknown(m)
}

var xxx_messageInfo_ScopedEvidenceVouch proto.InternalMessageInfo

func (m *ScopedEvidenceVouch) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ScopedEvidenceVouch) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetWeight() uint64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ScopedEvidenceVouch) GetArtifactUri() string {
	if m != nil {
		return m.ArtifactUri
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetArtifactSha256() string {
	if m != nil {
		return m.ArtifactSha256
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetEvidenceUri() string {
	if m != nil {
		return m.EvidenceUri
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetEvidenceSha256() string {
	if m != nil {
		return m.EvidenceSha256
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetRationaleHash() string {
	if m != nil {
		return m.RationaleHash
	}
	return ""
}

func (m *ScopedEvidenceVouch) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterType((*ScopedEvidenceVouch)(nil), "agntcoin.agntcoin.v1.ScopedEvidenceVouch")
}

func init() {
	proto.RegisterFile("agntcoin/agntcoin/v1/evidence.proto", fileDescriptor_d1a73a065bf5dc8e)
}

var fileDescriptor_d1a73a065bf5dc8e = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0xcf, 0x4e, 0x2a, 0x31,
	0x14, 0xc6, 0xe9, 0xf0, 0xe7, 0xde, 0x29, 0xf7, 0x62, 0x52, 0x89, 0xe9, 0x42, 0x27, 0xa8, 0x31,
	0xb2, 0x62, 0x82, 0x46, 0xf7, 0x9a, 0x98, 0xe8, 0x16, 0xa2, 0x0b, 0x37, 0xa4, 0x74, 0x2a, 0x3d,
	0x11, 0xa7, 0x93, 0xb6, 0x83, 0xe8, 0x53, 0xf8, 0x58, 0x2e, 0x59, 0xba, 0x34, 0xb0, 0xf0, 0x35,
	0x0c, 0xa5, 0x33, 0xec, 0xce, 0xf9, 0x7d, 0x5f, 0x7f, 0x49, 0x73, 0xf0, 0x31, 0x9b, 0xa4, 0x96,
	0x2b, 0x48, 0xe3, 0x72, 0x98, 0xf5, 0x63, 0x31, 0x83, 0x44, 0xa4, 0x5c, 0xf4, 0x32, 0xad, 0xac,
	0x22, 0xed, 0x22, 0xeb, 0x95, 0xc3, 0xac, 0x7f, 0xf4, 0x13, 0xe0, 0xdd, 0x21, 0x57, 0x99, 0x48,
	0x6e, 0x7c, 0xfd, 0x41, 0xe5, 0x5c, 0x92, 0x16, 0x0e, 0x20, 0xa1, 0xa8, 0x83, 0xba, 0xb5, 0x41,
	0x00, 0x09, 0xd9, 0xc3, 0x0d, 0x30, 0x26, 0x17, 0x9a, 0x06, 0x1d, 0xd4, 0x0d, 0x07, 0x7e, 0x23,
	0xfb, 0x38, 0xd4, 0x82, 0x43, 0x06, 0x22, 0xb5, 0xb4, 0xea, 0xa2, 0x2d, 0x20, 0x6d, 0x5c, 0x37,
	0x6b, 0x39, 0xad, 0xb9, 0x64, 0xb3, 0xac, 0x5d, 0xaf, 0x02, 0x26, 0xd2, 0xd2, 0xba, 0xf3, 0xfb,
	0x8d, 0x1c, 0xe2, 0x7f, 0x4c, 0x5b, 0x78, 0x62, 0xdc, 0x8e, 0x72, 0x0d, 0xb4, 0xe1, 0x1e, 0x35,
	0x0b, 0x76, 0xaf, 0x81, 0x9c, 0xe2, 0x9d, 0xb2, 0x62, 0x24, 0x3b, 0xbb, 0xb8, 0xa4, 0x7f, 0x5c,
	0xab, 0x55, 0xe0, 0xa1, 0xa3, 0x6b, 0x57, 0xf1, 0x7f, 0xe7, 0xfa, 0xbb, 0x71, 0x15, 0xcc, 0xbb,
	0xca, 0x8a, 0x77, 0x85, 0x1b, 0x57, 0x81, 0xbd, 0xeb, 0x04, 0xb7, 0x34, 0xb3, 0xa0, 0x52, 0x36,
	0x15, 0x23, 0xc9, 0x8c, 0xa4, 0xd8, 0xf5, 0xfe, 0x97, 0xf4, 0x96, 0x19, 0x49, 0x0e, 0x30, 0x16,
	0xf3, 0x0c, 0xb4, 0x30, 0x23, 0x66, 0x69, 0xb3, 0x83, 0xba, 0xd5, 0x41, 0xe8, 0xc9, 0x95, 0xbd,
	0xbe, 0xfb, 0x5c, 0x46, 0x68, 0xb1, 0x8c, 0xd0, 0xf7, 0x32, 0x42, 0x1f, 0xab, 0xa8, 0xb2, 0x58,
	0x45, 0x95, 0xaf, 0x55, 0x54, 0x79, 0x8c, 0x27, 0x60, 0x65, 0x3e, 0xee, 0x71, 0xf5, 0x12, 0xbf,
	0xab, 0xa9, 0x65, 0xe9, 0x33, 0x18, 0xb3, 0xbd, 0xe5, 0x7c, 0x3b, 0xda, 0xb7, 0x4c, 0x98, 0x71,
	0xc3, 0x5d, 0xf4, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x59, 0x94, 0xc0, 0xb0, 0xf8, 0x01, 0x00,
	0x00,
}

func (m *ScopedEvidenceVouch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScopedEvidenceVouch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScopedEvidenceVouch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintEvidence(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x58
	}
	if len(m.RationaleHash) > 0 {
		i -= len(m.RationaleHash)
		copy(dAtA[i:], m.RationaleHash)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.RationaleHash)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.EvidenceSha256) > 0 {
		i -= len(m.EvidenceSha256)
		copy(dAtA[i:], m.EvidenceSha256)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.EvidenceSha256)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.EvidenceUri) > 0 {
		i -= len(m.EvidenceUri)
		copy(dAtA[i:], m.EvidenceUri)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.EvidenceUri)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ArtifactSha256) > 0 {
		i -= len(m.ArtifactSha256)
		copy(dAtA[i:], m.ArtifactSha256)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.ArtifactSha256)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ArtifactUri) > 0 {
		i -= len(m.ArtifactUri)
		copy(dAtA[i:], m.ArtifactUri)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.ArtifactUri)))
		i--
		dAtA[i] = 0x32
	}
	if m.Weight != 0 {
		i = encodeVarintEvidence(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Scope) > 0 {
		i -= len(m.Scope)
		copy(dAtA[i:], m.Scope)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.Scope)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintEvidence(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvidence(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvidence(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ScopedEvidenceVouch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovEvidence(uint64(m.Id))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.Scope)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovEvidence(uint64(m.Weight))
	}
	l = len(m.ArtifactUri)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.ArtifactSha256)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.EvidenceUri)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.EvidenceSha256)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.RationaleHash)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovEvidence(uint64(m.ExpiresAt))
	}
	return n
}

func sovEvidence(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvidence(x uint64) (n int) {
	return sovEvidence(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ScopedEvidenceVouch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvidence
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScopedEvidenceVouch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScopedEvidenceVouch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArtifactUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArtifactUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArtifactSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArtifactSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RationaleHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RationaleHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvidence(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvidence
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvidence(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvidence
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvidence
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvidence
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvidence
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvidence        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvidence          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvidence = fmt.Errorf("proto: unexpected end of group")
)
