// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agntcoin/agntcoin/v1/gate.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Gate is one reCAPTCHA-style verification gate (gate-v1, 0.4.0): a slice of
// verification work streamed to the agent pool. Agents commit hashed answers
// during the commit window, reveal them during the reveal window (reveals
// only open AFTER commits close, so copying an answer is impossible by
// construction), and coherent answers MINT a tiny drip — the EARNED FAUCET
// and the first PoUW mint rail. A 0-coin 0-rep agent's first working capital
// comes from calibrated verification labor, not a free drip (the old faucet's
// sybil hole).
//
// DECOY vs LIVE: a decoy gate has a known gold verdict precommitted in
// gold_commit = sha256("<gold_answer>:<salt>"); a live gate commits the empty
// answer, sha256(":<salt>"). The two are BYTE-IDENTICAL on-chain until
// settlement — an answerer can never tell whether it is being calibrated or
// doing real work, so "answer honestly always" is the only coherent policy.
// Settlement: a revealed non-empty gold answer pays exact matches (decoy);
// an empty gold answer pays the strict-plurality answer (live consensus);
// a tie pays nobody.
//
// v1 limitations (documented, deliberate):
//   - posting is ANCHOR-only: the drip is minted supply, so emission authority
//     stays with the trust roots until the no-self-mining inequality
//     (drip per deal < fees + capital cost of the deal) is enforced in state;
//   - participation is self-selected (any registered agent), not sortition;
//     rep-weighted random assignment (reservoir sampling) lands with the
//     trials module;
//   - no vesting/slash of prior drip yet: the anti-guesser teeth in v1 are
//     k-ary answers + decoy density + pay-on-coherence-only.
type Gate struct {
	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Poster string `protobuf:"bytes,2,opt,name=poster,proto3" json:"poster,omitempty"`
	// payload_uri / payload_hash: where the gate's task content lives and the
	// hex sha256 the fetched bytes must match (same evidence discipline as
	// escrow delivery_hash — the chain pins, never stores, content).
	PayloadUri  string `protobuf:"bytes,3,opt,name=payload_uri,json=payloadUri,proto3" json:"payload_uri,omitempty"`
	PayloadHash string `protobuf:"bytes,4,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	// gold_commit: hex sha256("<gold_answer>:<salt>"). Non-empty gold_answer =
	// decoy; empty = live. Indistinguishable until the poster reveals at settle.
	GoldCommit string `protobuf:"bytes,5,opt,name=gold_commit,json=goldCommit,proto3" json:"gold_commit,omitempty"`
	// drip: microcoin MINTED per coherent answer at settlement (<= MaxDripPerAnswer).
	Drip       uint64 `protobuf:"varint,6,opt,name=drip,proto3" json:"drip,omitempty"`
	MaxAnswers uint64 `protobuf:"varint,7,opt,name=max_answers,json=maxAnswers,proto3" json:"max_answers,omitempty"`
	// commit_deadline / reveal_deadline: block time at post + the two windows.
	// Commits land strictly before commit_deadline; reveals strictly between
	// commit_deadline and reveal_deadline; settle at/after reveal_deadline.
	CommitDeadline int64 `protobuf:"varint,8,opt,name=commit_deadline,json=commitDeadline,proto3" json:"commit_deadline,omitempty"`
	RevealDeadline int64 `protobuf:"varint,9,opt,name=reveal_deadline,json=revealDeadline,proto3" json:"reveal_deadline,omitempty"`
	// status: "open" | "settled".
	Status  string        `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Answers []*GateAnswer `protobuf:"bytes,11,rep,name=answers,proto3" json:"answers,omitempty"`
	// Settlement record: the revealed gold answer ("" for live gates) and the
	// answer that paid ("" if nothing paid — tie or no coherent reveals).
	GoldAnswer string `protobuf:"bytes,12,opt,name=gold_answer,json=goldAnswer,proto3" json:"gold_answer,omitempty"`
	Consensus  string `protobuf:"bytes,13,opt,name=consensus,proto3" json:"consensus,omitempty"`
}

func (m *Gate) Reset()         { *m = Gate{} }
func (m *Gate) String() string { return proto.CompactTextString(m) }
func (*Gate) ProtoMessage()    {}
func (*Gate) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef56bdd04c3be20, []int{0}
}
func (m *Gate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Gate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Gate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Gate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gate.Merge(m, src)
}
func (m *Gate) XXX_Size() int {
	return m.Size()
}
func (m *Gate) XXX_DiscardUnknown() {
	xxx_messageInfo_Gate.DiscardUnknown(m)
}

var xxx_messageInfo_Gate proto.InternalMessageInfo

func (m *Gate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gate) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *Gate) GetPayloadUri() string {
	if m != nil {
		return m.PayloadUri
	}
	return ""
}

func (m *Gate) GetPayloadHash() string {
	if m != nil {
		return m.PayloadHash
	}
	return ""
}

func (m *Gate) GetGoldCommit() string {
	if m != nil {
		return m.GoldCommit
	}
	return ""
}

func (m *Gate) GetDrip() uint64 {
	if m != nil {
		return m.Drip
	}
	return 0
}

func (m *Gate) GetMaxAnswers() uint64 {
	if m != nil {
		return m.MaxAnswers
	}
	return 0
}

func (m *Gate) GetCommitDeadline() int64 {
	if m != nil {
		return m.CommitDeadline
	}
	return 0
}

func (m *Gate) GetRevealDeadline() int64 {
	if m != nil {
		return m.RevealDeadline
	}
	return 0
}

func (m *Gate) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Gate) GetAnswers() []*GateAnswer {
	if m != nil {
		return m.Answers
	}
	return nil
}

func (m *Gate) GetGoldAnswer() string {
	if m != nil {
		return m.GoldAnswer
	}
	return ""
}

func (m *Gate) GetConsensus() string {
	if m != nil {
		return m.Consensus
	}
	return ""
}

// GateAnswer is one agent's commit-reveal answer to a gate.
type GateAnswer struct {
	Agent string `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// commit: hex sha256("<answer>:<salt>"), posted during the commit window.
	Commit string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// answer: the revealed plaintext ("" until revealed). k-ary by convention
	// (e.g. "pass" / "fail:item3") — richer answers crush the guess rate.
	Answer   string `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Revealed bool   `protobuf:"varint,4,opt,name=revealed,proto3" json:"revealed,omitempty"`
	// paid: whether this answer earned the drip at settlement.
	Paid bool `protobuf:"varint,5,opt,name=paid,proto3" json:"paid,omitempty"`
}

func (m *GateAnswer) Reset()         { *m = GateAnswer{} }
func (m *GateAnswer) String() string { return proto.CompactTextString(m) }
func (*GateAnswer) ProtoMessage()    {}
func (*GateAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef56bdd04c3be20, []int{1}
}
func (m *GateAnswer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GateAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GateAnswer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GateAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateAnswer.Merge(m, src)
}
func (m *GateAnswer) XXX_Size() int {
	return m.Size()
}
func (m *GateAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_GateAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_GateAnswer proto.InternalMessageInfo

func (m *GateAnswer) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *GateAnswer) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *GateAnswer) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *GateAnswer) GetRevealed() bool {
	if m != nil {
		return m.Revealed
	}
	return false
}

func (m *GateAnswer) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func init() {
	proto.RegisterType((*Gate)(nil), "agntcoin.agntcoin.v1.Gate")
	proto.RegisterType((*GateAnswer)(nil), "agntcoin.agntcoin.v1.GateAnswer")
}

func init() { proto.RegisterFile("agntcoin/agntcoin/v1/gate.proto", fileDescriptor_fef56bdd04c3be20) }

var fileDescriptor_fef56bdd04c3be20 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xbd, 0x8e, 0x13, 0x31,
	0x10, 0x8e, 0x93, 0x5c, 0x2e, 0x99, 0x1c, 0x87, 0x64, 0x9d, 0x4e, 0x16, 0x42, 0x7b, 0xcb, 0x35,
	0xa4, 0xda, 0xe8, 0xa0, 0xa3, 0xe3, 0x47, 0x02, 0xda, 0x95, 0x68, 0x68, 0xa2, 0xb9, 0xd8, 0xda,
	0xb5, 0xd8, 0xb5, 0x57, 0x6b, 0x6f, 0xc8, 0x51, 0xf2, 0x04, 0xbc, 0x08, 0xef, 0x41, 0x99, 0x92,
	0x12, 0x25, 0x2f, 0x82, 0x6c, 0xef, 0x4f, 0x73, 0xdd, 0x7c, 0xdf, 0x7c, 0x33, 0x9e, 0x99, 0xcf,
	0x70, 0x83, 0x99, 0xb2, 0x5b, 0x2d, 0xd5, 0xba, 0x0f, 0x76, 0x77, 0xeb, 0x0c, 0xad, 0x48, 0xaa,
	0x5a, 0x5b, 0x4d, 0xaf, 0x3a, 0x3e, 0xe9, 0x83, 0xdd, 0xdd, 0xed, 0xef, 0x09, 0x4c, 0x3f, 0xa2,
	0x15, 0xf4, 0x12, 0xc6, 0x92, 0x33, 0x12, 0x93, 0xd5, 0x34, 0x1d, 0x4b, 0x4e, 0xaf, 0x61, 0x56,
	0x69, 0x63, 0x45, 0xcd, 0xc6, 0x31, 0x59, 0x2d, 0xd2, 0x16, 0xd1, 0x1b, 0x58, 0x56, 0xf8, 0x50,
	0x68, 0xe4, 0x9b, 0xa6, 0x96, 0x6c, 0xe2, 0x93, 0xd0, 0x52, 0x5f, 0x6a, 0x49, 0x5f, 0xc0, 0x45,
	0x27, 0xc8, 0xd1, 0xe4, 0x6c, 0xea, 0x15, 0x5d, 0xd1, 0x27, 0x34, 0xb9, 0xeb, 0x91, 0xe9, 0x82,
	0x6f, 0xb6, 0xba, 0x2c, 0xa5, 0x65, 0x67, 0xa1, 0x87, 0xa3, 0xde, 0x7b, 0x86, 0x52, 0x98, 0xf2,
	0x5a, 0x56, 0x6c, 0xe6, 0xc7, 0xf1, 0xb1, 0x2b, 0x2a, 0x71, 0xbf, 0x41, 0x65, 0xbe, 0x8b, 0xda,
	0xb0, 0x73, 0x9f, 0x82, 0x12, 0xf7, 0x6f, 0x03, 0x43, 0x5f, 0xc2, 0xd3, 0xd0, 0x70, 0xc3, 0x05,
	0xf2, 0x42, 0x2a, 0xc1, 0xe6, 0x31, 0x59, 0x4d, 0xd2, 0xcb, 0x40, 0x7f, 0x68, 0x59, 0x27, 0xac,
	0xc5, 0x4e, 0x60, 0x31, 0x08, 0x17, 0x41, 0x18, 0xe8, 0x5e, 0x78, 0x0d, 0x33, 0x63, 0xd1, 0x36,
	0x86, 0x41, 0xb8, 0x41, 0x40, 0xf4, 0x0d, 0x9c, 0x77, 0x63, 0x2c, 0xe3, 0xc9, 0x6a, 0xf9, 0x2a,
	0x4e, 0x1e, 0x3b, 0x6e, 0xe2, 0x0e, 0x1b, 0xa6, 0x4b, 0xbb, 0x82, 0x7e, 0xf7, 0x80, 0xd9, 0xc5,
	0xb0, 0x7b, 0x50, 0xd2, 0xe7, 0xb0, 0xd8, 0x6a, 0x65, 0x84, 0x32, 0x8d, 0x61, 0x4f, 0x7c, 0x7a,
	0x20, 0x6e, 0x7f, 0x12, 0x80, 0xa1, 0x2d, 0xbd, 0x82, 0x33, 0xcc, 0x84, 0xb2, 0xde, 0xb8, 0x45,
	0x1a, 0x80, 0x9b, 0xbb, 0x3d, 0x6d, 0xeb, 0x5d, 0x40, 0x8e, 0x6f, 0x9f, 0x0d, 0xb6, 0xb5, 0x88,
	0x3e, 0x83, 0x79, 0xd8, 0x5c, 0x70, 0x6f, 0xd7, 0x3c, 0xed, 0xb1, 0xb3, 0xa2, 0x42, 0xc9, 0xbd,
	0x49, 0xf3, 0xd4, 0xc7, 0xef, 0x3e, 0xff, 0x39, 0x46, 0xe4, 0x70, 0x8c, 0xc8, 0xbf, 0x63, 0x44,
	0x7e, 0x9d, 0xa2, 0xd1, 0xe1, 0x14, 0x8d, 0xfe, 0x9e, 0xa2, 0xd1, 0xd7, 0x75, 0x26, 0x6d, 0xde,
	0xdc, 0x27, 0x5b, 0x5d, 0xae, 0x7f, 0xe8, 0xc2, 0xa2, 0xfa, 0x26, 0x8d, 0x19, 0xbe, 0xe4, 0x7e,
	0x08, 0xed, 0x43, 0x25, 0xcc, 0xfd, 0xcc, 0x7f, 0xce, 0xd7, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xe0, 0x8f, 0xc9, 0x2c, 0xbf, 0x02, 0x00, 0x00,
}

func (m *Gate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Gate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Gate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Consensus) > 0 {
		i -= len(m.Consensus)
		copy(dAtA[i:], m.Consensus)
		i = encodeVarintGate(dAtA, i, uint64(len(m.Consensus)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.GoldAnswer) > 0 {
		i -= len(m.GoldAnswer)
		copy(dAtA[i:], m.GoldAnswer)
		i = encodeVarintGate(dAtA, i, uint64(len(m.GoldAnswer)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Answers) > 0 {
		for iNdEx := len(m.Answers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Answers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGate(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintGate(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x52
	}
	if m.RevealDeadline != 0 {
		i = encodeVarintGate(dAtA, i, uint64(m.RevealDeadline))
		i--
		dAtA[i] = 0x48
	}
	if m.CommitDeadline != 0 {
		i = encodeVarintGate(dAtA, i, uint64(m.CommitDeadline))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxAnswers != 0 {
		i = encodeVarintGate(dAtA, i, uint64(m.MaxAnswers))
		i--
		dAtA[i] = 0x38
	}
	if m.Drip != 0 {
		i = encodeVarintGate(dAtA, i, uint64(m.Drip))
		i--
		dAtA[i] = 0x30
	}
	if len(m.GoldCommit) > 0 {
		i -= len(m.GoldCommit)
		copy(dAtA[i:], m.GoldCommit)
		i = encodeVarintGate(dAtA, i, uint64(len(m.GoldCommit)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PayloadHash) > 0 {
		i -= len(m.PayloadHash)
		copy(dAtA[i:], m.PayloadHash)
		i = encodeVarintGate(dAtA, i, uint64(len(m.PayloadHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PayloadUri) > 0 {
		i -= len(m.PayloadUri)
		copy(dAtA[i:], m.PayloadUri)
		i = encodeVarintGate(dAtA, i, uint64(len(m.PayloadUri)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Poster) > 0 {
		i -= len(m.Poster)
		copy(dAtA[i:], m.Poster)
		i = encodeVarintGate(dAtA, i, uint64(len(m.Poster)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintGate(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GateAnswer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GateAnswer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GateAnswer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Paid {
		i--
		if m.Paid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Revealed {
		i--
		if m.Revealed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Answer) > 0 {
		i -= len(m.Answer)
		copy(dAtA[i:], m.Answer)
		i = encodeVarintGate(dAtA, i, uint64(len(m.Answer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Commit) > 0 {
		i -= len(m.Commit)
		copy(dAtA[i:], m.Commit)
		i = encodeVarintGate(dAtA, i, uint64(len(m.Commit)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Agent) > 0 {
		i -= len(m.Agent)
		copy(dAtA[i:], m.Agent)
		i = encodeVarintGate(dAtA, i, uint64(len(m.Agent)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGate(dAtA []byte, offset int, v uint64) int {
	offset -= sovGate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Gate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGate(uint64(m.Id))
	}
	l = len(m.Poster)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	l = len(m.PayloadUri)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	l = len(m.PayloadHash)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	l = len(m.GoldCommit)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	if m.Drip != 0 {
		n += 1 + sovGate(uint64(m.Drip))
	}
	if m.MaxAnswers != 0 {
		n += 1 + sovGate(uint64(m.MaxAnswers))
	}
	if m.CommitDeadline != 0 {
		n += 1 + sovGate(uint64(m.CommitDeadline))
	}
	if m.RevealDeadline != 0 {
		n += 1 + sovGate(uint64(m.RevealDeadline))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	if len(m.Answers) > 0 {
		for _, e := range m.Answers {
			l = e.Size()
			n += 1 + l + sovGate(uint64(l))
		}
	}
	l = len(m.GoldAnswer)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	l = len(m.Consensus)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	return n
}

func (m *GateAnswer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Agent)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	l = len(m.Commit)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	l = len(m.Answer)
	if l > 0 {
		n += 1 + l + sovGate(uint64(l))
	}
	if m.Revealed {
		n += 2
	}
	if m.Paid {
		n += 2
	}
	return n
}

func sovGate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGate(x uint64) (n int) {
	return sovGate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Gate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Gate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Gate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poster", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Poster = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayloadUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayloadHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoldCommit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoldCommit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Drip", wireType)
			}
			m.Drip = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Drip |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAnswers", wireType)
			}
			m.MaxAnswers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAnswers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitDeadline", wireType)
			}
			m.CommitDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitDeadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealDeadline", wireType)
			}
			m.RevealDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevealDeadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = append(m.Answers, &GateAnswer{})
			if err := m.Answers[len(m.Answers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoldAnswer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoldAnswer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consensus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Consensus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GateAnswer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GateAnswer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GateAnswer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revealed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Revealed = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGate = fmt.Errorf("proto: unexpected end of group")
)
