// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agntcoin/agntcoin/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the agntcoin module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params                   Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	AccountMap               []Account             `protobuf:"bytes,2,rep,name=account_map,json=accountMap,proto3" json:"account_map"`
	VouchList                []Vouch               `protobuf:"bytes,3,rep,name=vouch_list,json=vouchList,proto3" json:"vouch_list"`
	VouchCount               uint64                `protobuf:"varint,4,opt,name=vouch_count,json=vouchCount,proto3" json:"vouch_count,omitempty"`
	EscrowList               []Escrow              `protobuf:"bytes,5,rep,name=escrow_list,json=escrowList,proto3" json:"escrow_list"`
	EscrowCount              uint64                `protobuf:"varint,6,opt,name=escrow_count,json=escrowCount,proto3" json:"escrow_count,omitempty"`
	ContributionAwardList    []ContributionAward   `protobuf:"bytes,7,rep,name=contribution_award_list,json=contributionAwardList,proto3" json:"contribution_award_list"`
	ContributionAwardCount   uint64                `protobuf:"varint,8,opt,name=contribution_award_count,json=contributionAwardCount,proto3" json:"contribution_award_count,omitempty"`
	ScopedEvidenceVouchList  []ScopedEvidenceVouch `protobuf:"bytes,9,rep,name=scoped_evidence_vouch_list,json=scopedEvidenceVouchList,proto3" json:"scoped_evidence_vouch_list"`
	ScopedEvidenceVouchCount uint64                `protobuf:"varint,10,opt,name=scoped_evidence_vouch_count,json=scopedEvidenceVouchCount,proto3" json:"scoped_evidence_vouch_count,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_eccf4e1f2a352dfb, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetAccountMap() []Account {
	if m != nil {
		return m.AccountMap
	}
	return nil
}

func (m *GenesisState) GetVouchList() []Vouch {
	if m != nil {
		return m.VouchList
	}
	return nil
}

func (m *GenesisState) GetVouchCount() uint64 {
	if m != nil {
		return m.VouchCount
	}
	return 0
}

func (m *GenesisState) GetEscrowList() []Escrow {
	if m != nil {
		return m.EscrowList
	}
	return nil
}

func (m *GenesisState) GetEscrowCount() uint64 {
	if m != nil {
		return m.EscrowCount
	}
	return 0
}

func (m *GenesisState) GetContributionAwardList() []ContributionAward {
	if m != nil {
		return m.ContributionAwardList
	}
	return nil
}

func (m *GenesisState) GetContributionAwardCount() uint64 {
	if m != nil {
		return m.ContributionAwardCount
	}
	return 0
}

func (m *GenesisState) GetScopedEvidenceVouchList() []ScopedEvidenceVouch {
	if m != nil {
		return m.ScopedEvidenceVouchList
	}
	return nil
}

func (m *GenesisState) GetScopedEvidenceVouchCount() uint64 {
	if m != nil {
		return m.ScopedEvidenceVouchCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "agntcoin.agntcoin.v1.GenesisState")
}

func init() {
	proto.RegisterFile("agntcoin/agntcoin/v1/genesis.proto", fileDescriptor_eccf4e1f2a352dfb)
}

var fileDescriptor_eccf4e1f2a352dfb = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x6f, 0x58, 0x57, 0xa8, 0xb3, 0x0b, 0xd1, 0x60, 0x51, 0x07, 0x59, 0x37, 0x0e, 0x2b, 0x1c,
	0x12, 0x6d, 0x5c, 0xb8, 0x20, 0x58, 0xcb, 0x84, 0x90, 0x40, 0x42, 0x9d, 0xc4, 0x81, 0x4b, 0xe4,
	0xba, 0x56, 0x66, 0xd1, 0xda, 0x51, 0xec, 0x64, 0xc0, 0xa7, 0xe0, 0x63, 0x70, 0x42, 0x7c, 0x8c,
	0x1d, 0x77, 0xe4, 0x84, 0x50, 0x7b, 0xe0, 0x6b, 0xa0, 0xbc, 0xe7, 0x6e, 0x11, 0x33, 0x5c, 0xa2,
	0x27, 0xbf, 0xdf, 0x3f, 0xbf, 0x17, 0x93, 0x3d, 0x9a, 0x49, 0xc3, 0x94, 0x90, 0xc9, 0x65, 0x51,
	0x1d, 0x24, 0x19, 0x97, 0x5c, 0x0b, 0x1d, 0xe7, 0x85, 0x32, 0x2a, 0xd8, 0x5c, 0xb5, 0xe2, 0xcb,
	0xa2, 0x3a, 0xe8, 0xb9, 0x99, 0x94, 0x31, 0x55, 0x4a, 0x83, 0xcc, 0xde, 0xae, 0x13, 0x93, 0xd3,
	0x82, 0xce, 0xad, 0x78, 0xaf, 0xef, 0x84, 0x54, 0xaa, 0x64, 0xa7, 0xff, 0x15, 0xe1, 0x9a, 0x15,
	0xea, 0xcc, 0x42, 0xf6, 0x9d, 0x10, 0xa6, 0xa4, 0x29, 0xc4, 0xa4, 0x34, 0x42, 0x49, 0x0b, 0x7c,
	0xe0, 0xd6, 0xaa, 0xc4, 0x94, 0x4b, 0xc6, 0x2d, 0xe8, 0x36, 0x9d, 0x0b, 0xa9, 0x12, 0xf8, 0xda,
	0xa3, 0xcd, 0x4c, 0x65, 0x0a, 0xca, 0xa4, 0xae, 0xf0, 0x74, 0xef, 0xdb, 0x3a, 0xd9, 0x78, 0x89,
	0xa3, 0x3a, 0x31, 0xd4, 0xf0, 0xe0, 0x19, 0xe9, 0xe0, 0xe5, 0x42, 0xaf, 0xef, 0x0d, 0xfc, 0xc3,
	0x7b, 0xb1, 0x6b, 0x74, 0xf1, 0x5b, 0xc0, 0x0c, 0xbb, 0xe7, 0x3f, 0x77, 0x5a, 0x5f, 0x7f, 0x7f,
	0x7f, 0xe4, 0x8d, 0x2d, 0x2d, 0x78, 0x41, 0x7c, 0x3b, 0xc1, 0x74, 0x4e, 0xf3, 0xf0, 0x46, 0x7f,
	0x6d, 0xe0, 0x1f, 0xde, 0x77, 0xab, 0x1c, 0x21, 0x70, 0xd8, 0xae, 0x65, 0xc6, 0xc4, 0xf2, 0xde,
	0xd0, 0x3c, 0x78, 0x4e, 0x08, 0x0c, 0x30, 0x9d, 0x09, 0x6d, 0xc2, 0x35, 0x10, 0xd9, 0x76, 0x8b,
	0xbc, 0xab, 0x71, 0x56, 0xa2, 0x0b, 0xa4, 0xd7, 0x42, 0x9b, 0x60, 0x87, 0xf8, 0xa8, 0x00, 0x9a,
	0x61, 0xbb, 0xef, 0x0d, 0xda, 0x63, 0x14, 0x1d, 0xd5, 0x27, 0xc1, 0x88, 0xf8, 0xb8, 0x01, 0xf4,
	0x58, 0x07, 0x8f, 0x7f, 0x5c, 0xf7, 0x18, 0x80, 0xab, 0x9c, 0x48, 0x03, 0x97, 0x5d, 0xb2, 0x61,
	0x45, 0xd0, 0xa6, 0x03, 0x36, 0x56, 0x18, 0x7d, 0x38, 0xd9, 0x6a, 0xae, 0x31, 0xa5, 0x67, 0xb4,
	0x98, 0xa2, 0xe7, 0x4d, 0xf0, 0xdc, 0x77, 0x7b, 0x8e, 0x1a, 0xa4, 0xa3, 0x9a, 0x63, 0xed, 0xef,
	0xb0, 0xbf, 0x1b, 0x90, 0xe4, 0x09, 0x09, 0x1d, 0x36, 0x98, 0xea, 0x16, 0xa4, 0xba, 0x7b, 0x8d,
	0x88, 0x01, 0x67, 0xa4, 0xa7, 0x99, 0xca, 0xf9, 0x34, 0x5d, 0xfd, 0x45, 0x69, 0x63, 0xf6, 0x5d,
	0xc8, 0xf8, 0xd0, 0x9d, 0xf1, 0x04, 0x78, 0xc7, 0x96, 0xd6, 0xdc, 0xc4, 0x96, 0xbe, 0xde, 0x82,
	0x9c, 0x4f, 0xc9, 0xb6, 0xdb, 0x0d, 0xa3, 0x12, 0x88, 0x1a, 0x3a, 0xd8, 0x10, 0x76, 0xf8, 0xea,
	0x7c, 0x11, 0x79, 0x17, 0x8b, 0xc8, 0xfb, 0xb5, 0x88, 0xbc, 0x2f, 0xcb, 0xa8, 0x75, 0xb1, 0x8c,
	0x5a, 0x3f, 0x96, 0x51, 0xeb, 0x7d, 0x92, 0x09, 0x73, 0x5a, 0x4e, 0x62, 0xa6, 0xe6, 0xc9, 0x67,
	0x35, 0x33, 0x54, 0x7e, 0x10, 0x5a, 0x5f, 0xbd, 0x92, 0x8f, 0x57, 0xa5, 0xf9, 0x94, 0x73, 0x3d,
	0xe9, 0xc0, 0x13, 0x78, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0x93, 0x5b, 0x83, 0x3a, 0x41, 0x04,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ScopedEvidenceVouchCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ScopedEvidenceVouchCount))
		i--
		dAtA[i] = 0x50
	}
	if len(m.ScopedEvidenceVouchList) > 0 {
		for iNdEx := len(m.ScopedEvidenceVouchList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ScopedEvidenceVouchList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.ContributionAwardCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ContributionAwardCount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.ContributionAwardList) > 0 {
		for iNdEx := len(m.ContributionAwardList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContributionAwardList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.EscrowCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.EscrowCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.EscrowList) > 0 {
		for iNdEx := len(m.EscrowList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EscrowList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.VouchCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.VouchCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.VouchList) > 0 {
		for iNdEx := len(m.VouchList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VouchList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.AccountMap) > 0 {
		for iNdEx := len(m.AccountMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.AccountMap) > 0 {
		for _, e := range m.AccountMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.VouchList) > 0 {
		for _, e := range m.VouchList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.VouchCount != 0 {
		n += 1 + sovGenesis(uint64(m.VouchCount))
	}
	if len(m.EscrowList) > 0 {
		for _, e := range m.EscrowList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.EscrowCount != 0 {
		n += 1 + sovGenesis(uint64(m.EscrowCount))
	}
	if len(m.ContributionAwardList) > 0 {
		for _, e := range m.ContributionAwardList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ContributionAwardCount != 0 {
		n += 1 + sovGenesis(uint64(m.ContributionAwardCount))
	}
	if len(m.ScopedEvidenceVouchList) > 0 {
		for _, e := range m.ScopedEvidenceVouchList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ScopedEvidenceVouchCount != 0 {
		n += 1 + sovGenesis(uint64(m.ScopedEvidenceVouchCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountMap = append(m.AccountMap, Account{})
			if err := m.AccountMap[len(m.AccountMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VouchList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VouchList = append(m.VouchList, Vouch{})
			if err := m.VouchList[len(m.VouchList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VouchCount", wireType)
			}
			m.VouchCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VouchCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowList = append(m.EscrowList, Escrow{})
			if err := m.EscrowList[len(m.EscrowList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowCount", wireType)
			}
			m.EscrowCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EscrowCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionAwardList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributionAwardList = append(m.ContributionAwardList, ContributionAward{})
			if err := m.ContributionAwardList[len(m.ContributionAwardList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionAwardCount", wireType)
			}
			m.ContributionAwardCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContributionAwardCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopedEvidenceVouchList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScopedEvidenceVouchList = append(m.ScopedEvidenceVouchList, ScopedEvidenceVouch{})
			if err := m.ScopedEvidenceVouchList[len(m.ScopedEvidenceVouchList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopedEvidenceVouchCount", wireType)
			}
			m.ScopedEvidenceVouchCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScopedEvidenceVouchCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
